"""Validation fixtures and executable parity evidence."""

from .black_scholes_parity import (
    DEFAULT_TOLERANCE_ABSOLUTE,
    DEFAULT_TOLERANCE_RELATIVE,
    EXPECTED_BLACK_SCHOLES_CALL_PRICE,
    PUBLIC_SYNTHETIC_BLACK_SCHOLES_BENCHMARK_ID,
    PUBLIC_SYNTHETIC_PROBLEM_ID,
    BoundaryMetadata,
    ComparisonPolicy,
    FEMParityConvergenceRow,
    FEMParityReport,
    MeshMetadata,
    SensitivityReferencePolicy,
    TimeMetadata,
    WeakFormMetadata,
    build_fixture_config_hash,
    build_public_fem_bs_oracle_problem_spec,
    run_public_black_scholes_parity_fixture,
    write_public_fem_bs_oracle_spec,
    write_public_fem_bs_result_export,
    FEM_BS_001_PROBLEM_SPEC_PATH,
    FEM_BS_001_RESULT_EXPORT_PATH,
)

__all__ = [
    "DEFAULT_TOLERANCE_ABSOLUTE",
    "DEFAULT_TOLERANCE_RELATIVE",
    "EXPECTED_BLACK_SCHOLES_CALL_PRICE",
    "PUBLIC_SYNTHETIC_BLACK_SCHOLES_BENCHMARK_ID",
    "PUBLIC_SYNTHETIC_PROBLEM_ID",
    "BoundaryMetadata",
    "ComparisonPolicy",
    "FEMParityConvergenceRow",
    "FEMParityReport",
    "MeshMetadata",
    "SensitivityReferencePolicy",
    "TimeMetadata",
    "WeakFormMetadata",
    "build_fixture_config_hash",
    "build_public_fem_bs_oracle_problem_spec",
    "run_public_black_scholes_parity_fixture",
    "write_public_fem_bs_oracle_spec",
    "write_public_fem_bs_result_export",
    "FEM_BS_001_PROBLEM_SPEC_PATH",
    "FEM_BS_001_RESULT_EXPORT_PATH",
]
