#!/usr/bin/env python3
"""Generate and check capability documentation from the FEM registry."""

from __future__ import annotations

import argparse
import sys
from collections.abc import Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from finite_element_options.contracts.capability_matrix import (  # noqa: E402
    DEFAULT_CAPABILITY_RECORDS,
    CapabilityRecord,
)

DOC_PATH = ROOT / "docs" / "CAPABILITY_MATRIX.md"
README_PATH = ROOT / "README.md"
README_START_MARKER = "<!-- capability-matrix:start -->"
README_END_MARKER = "<!-- capability-matrix:end -->"
_GENERATED_NOTICE = "<!-- generated by scripts/generate_capability_docs.py; do not edit by hand -->"


def _cell(value: str | Sequence[str] | None) -> str:
    if value is None:
        return "—"
    if isinstance(value, str):
        text = value or "—"
    else:
        text = "<br>".join(value) if value else "—"
    return text.replace("|", "\\|").replace("\n", " ")


def _evidence(record: CapabilityRecord) -> str:
    parts = [*record.evidence_ids]
    parts.extend(f"benchmark:{item}" for item in record.benchmark_ids)
    parts.extend(f"reference:{item}" for item in record.reference_ids)
    return _cell(parts)


def render_readme_capability_snapshot(records: Sequence[CapabilityRecord]) -> str:
    """Render the compact README capability table."""

    lines = [
        "",
        "| Capability | Maturity | Evidence / benchmark | Limitation / absence behavior |",
        "|---|---|---|---|",
    ]
    for record in records:
        absence = f" Optional: {record.absence_behavior}" if record.absence_behavior else ""
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{_cell(record.capability_id)}` — {_cell(record.title)}",
                    _cell(record.status.value),
                    _evidence(record),
                    _cell(record.limitations + absence),
                ]
            )
            + " |"
        )
    lines.append("")
    return "\n".join(lines)


def render_capability_matrix_markdown(records: Sequence[CapabilityRecord]) -> str:
    """Render the full generated capability matrix document."""

    lines = [
        _GENERATED_NOTICE,
        "# FEM Capability Matrix",
        "",
        "This document is generated from",
        "`finite_element_options.contracts.capability_matrix`. It is the",
        "machine-backed source for public README capability claims and keeps",
        "maturity separate from mere code existence.",
        "",
        "## Maturity vocabulary",
        "",
        "| Status | Meaning |",
        "|---|---|",
        "| `scaffold` | Shape exists, but no advertised user-facing route. |",
        "| `experimental` | Optional or research route; do not treat as validated. |",
        "| `implemented` | Code exists with focused tests, but validation is incomplete. |",
        "| `validated` | Reference, regression, residual, or benchmark evidence exists. |",
        "| `production-qualified` | Release/contract evidence is suitable for consumers. |",
        "| `deprecated` | Compatibility only; replacement and removal policy are published. |",
        "| `unsupported` | Requests fail closed before expensive numerical work. |",
        "",
        "## Registry",
        "",
        "| ID | Capability | Status | Workstream | Evidence / benchmark | Optional profile / absence | Scope | Limitations |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for record in records:
        optional = record.optional_extra or "base"
        if record.absence_behavior:
            optional = f"{optional}<br>{record.absence_behavior}"
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{_cell(record.capability_id)}`",
                    _cell(f"{record.title}. {record.summary}"),
                    _cell(record.status.value),
                    _cell(record.workstream),
                    _evidence(record),
                    _cell(optional),
                    _cell(record.evidence_scope),
                    _cell(record.limitations),
                ]
            )
            + " |"
        )
    lines.extend(
        [
            "",
            "## Generated-doc contract",
            "",
            "Run this check before changing README claims or capability records:",
            "",
            "```bash",
            "python scripts/generate_capability_docs.py --check",
            "```",
            "",
            "Run this update command after intentional registry changes:",
            "",
            "```bash",
            "python scripts/generate_capability_docs.py --write",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def replace_readme_snapshot(readme: str, replacement: str) -> str:
    """Replace the generated README snapshot between capability markers."""

    if README_START_MARKER not in readme or README_END_MARKER not in readme:
        raise ValueError("README is missing capability-matrix markers")
    start = readme.index(README_START_MARKER) + len(README_START_MARKER)
    end = readme.index(README_END_MARKER)
    return readme[:start] + replacement + readme[end:]


def write_docs() -> None:
    """Write generated capability docs and README snapshot."""

    DOC_PATH.write_text(
        render_capability_matrix_markdown(DEFAULT_CAPABILITY_RECORDS),
        encoding="utf-8",
    )
    readme = README_PATH.read_text(encoding="utf-8")
    README_PATH.write_text(
        replace_readme_snapshot(
            readme,
            render_readme_capability_snapshot(DEFAULT_CAPABILITY_RECORDS),
        ),
        encoding="utf-8",
    )


def check_docs() -> list[str]:
    """Return staleness errors for generated docs."""

    errors: list[str] = []
    expected_doc = render_capability_matrix_markdown(DEFAULT_CAPABILITY_RECORDS)
    if not DOC_PATH.exists():
        errors.append(f"missing generated doc: {DOC_PATH.relative_to(ROOT)}")
    elif DOC_PATH.read_text(encoding="utf-8") != expected_doc:
        errors.append(f"stale generated doc: {DOC_PATH.relative_to(ROOT)}")

    expected_snapshot = render_readme_capability_snapshot(DEFAULT_CAPABILITY_RECORDS)
    readme = README_PATH.read_text(encoding="utf-8")
    try:
        rendered = replace_readme_snapshot(readme, expected_snapshot)
    except ValueError as exc:
        errors.append(str(exc))
    else:
        if rendered != readme:
            errors.append("stale generated README capability matrix")
    return errors


def main(argv: Sequence[str] | None = None) -> int:
    """CLI entry point."""

    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail if docs are stale")
    mode.add_argument("--write", action="store_true", help="rewrite generated docs")
    args = parser.parse_args(argv)

    if args.write:
        write_docs()
        print("Generated capability docs")
        return 0

    errors = check_docs()
    if errors:
        print("Capability documentation is stale:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        print("Run: python scripts/generate_capability_docs.py --write", file=sys.stderr)
        return 1
    print("Capability documentation is current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
